# Generated by Django 5.0.7 on 2024-07-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/null.jpg', upload_to='products'),
        ),
    ]
