# Generated by Django 5.0.7 on 2024-08-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0009_category_image_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='siteadmin.cartitem')),
            ],
        ),
    ]
