# Generated by Django 5.0.7 on 2024-08-06 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0012_remove_purchase_cart_item_purchase_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.user')),
            ],
        ),
    ]
