# Generated by Django 5.0.7 on 2024-08-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0014_rename_text_review_details_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='This will be the product description.'),
        ),
    ]
